menu:
  animation:
    type: "wave" # fill_glass, wave, random_fill
    material: "LIGHT_BLUE_STAINED_GLASS_PANE"
    speed: 5  # Задержка между кадрами в тиках (20L = 1 сек)
    sound: BLOCK_NOTE_BLOCK_BANJO #звук, который будет проигрываться